title: "allwater"
author: "allwater-cmd"
description: "many things water" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
# email: "kyle.mitchell@tetratech.com"
# twitter_username: "twitteruser"
# github_username: "githubuser"
# linkedin_username: "kyleptmitchell"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

markdown: kramdown 

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      image: https://s.gravatar.com/avatar/7aada0181eaba02bf691f8fc6c920bfb622b34ac8d17a3574d7d88f96495b12d?s=800
      tags: 
        - Other # Add a default tag to all posts

home_post_limit: 5

gravatar_hash: 7aada0181eaba02bf691f8fc6c920bfb622b34ac8d17a3574d7d88f96495b12d
code_block_max_height: 500px
